description: Hack the Burgh, the hackathon from beyond the wall, will be returning soon.

sass:
   sourcemap: true

navigation:
  - text: Home
    url: \#
  - text: FAQ
    url: \#faq
  - text: History
    url: \#history
