description: Hack the Burgh, the hackathon from beyond the wall, will be returning soon.

sass:
   sourcemap: true

navigation:
  - text: Home
    url: \#
  - text: FAQ
    url: \#faq
  - text: Find us
    url: \#location
  - text: Explore 2015
    url: http://2015.hacktheburgh.com
  - text: Explore 2016
    url: http://2016.hacktheburgh.com
